### ISSUE TITLE
Težave pri dokončevanju projekta

### ISSUE THREAD

**Issue by MatijaGH** [MatijaGH/APPR-2017-18#1]
Imam par vprašanj glede projekta pri APPR.
Ko zaženem datoteko projekt.Rmd, mi izpiše poročilo, a javlja veliko napak, ta sporočila bi rad odpravil. 
Moral sem zakomentirati celo datoteko vizualizacija, saj se mi pri prevajanju poročila pojavlja napaka, da z nekaj ni v redu, javlja, da ne najde tabel, ki jih uporabljam pri vizualiziranju. 
Na koncu poročila mi sporoča, da ne najde datoteke valute, ko delam s Shinyjem.
Ne deluje tudi povezava na Binder, ki je v poročilu zakomentirana v vrsticah 41-44.
Prosim vas za pomoč.

Hvala in lep pozdrav

**Comment by jaanos** [comment]
Do večine opozoril pride pri uvozu - znebiš se jih tako, da v ustrezno glavo bloka kode dodaš parameter `warning=FALSE` (kot ga ponekod že imaš). Pri uvozu zemljevida se izpiše sporočilo, ki ga ni mogoče skriti na tak način, zato svetujem, da ga premakneš v `vizualizacija.r` (sam izris naj bo seveda v poročilu), v glavi bloka kode, kjer kličeš ta program, pa dodaš parameter `results='hide'`, da se izhod ne bo izpisoval.

Pri meni pride do napake pri izvajanju `uvoz.r` - težava je tukaj:
https://github.com/MatijaGH/APPR-2017-18/blob/3827f43c8dd6e37141ef9ca49d82b15f0a6a672f/uvoz/uvoz.r#L51
Tukaj se pojavi edini šumnik, ki pa je zapisan s kodiranjem znakov *WINDOWS-1250*, medtem ko program pričakuje kodiranje znakov *UTF-8*. V izogib nadaljnjim problemom se prepričaj, da imaš v RStudiu odprt projekt - če desno zgoraj piše *Project: (None)*, klikni tja, izberi *Open Project...*, nato pa poišči datoteko `APPR-2017-18.Rproj` v mapi svojega repozitorija (tako bo deloval tudi git znotraj RStudia). Potem lahko odpreš `uvoz.r` in popraviš zgornji šumnik - če se pa pravilno prikaže, pa izberi *File* / *Save with Encoding...* in tam izberi *UTF-8*.

V nadaljevanju programa `uvoz.r` se sklicuješ na spremenljivko `valute` (z malo začetnico), medtem ko pred tem definiraš le razpredelnico `Valute` (z veliko začetnico), zato pride do napake (tudi kasneje v Shinyju). Morda so podobne narave tudi napake, ki so se ti pojavljale v `vizualizacija.r`.

Eno od opozoril se nanaša tudi na to, da je način uvažanja zemljevida (iz lanske predloge) zastarel. Zato svetujem, da nadomestiš program `uvozi.zemljevid.r` z [novejšo različico](https://github.com/jaanos/APPR-2018-19/blob/master/lib/uvozi.zemljevid.r). Ta več ne vsebuje funkcije `pretvori.zemljevid` - nadomešča jo funkcija `fortify`, ki opravi isto delo.

Opažam, da imaš v poročilu sliko, ki je pa na repozitoriju ni. Da ti bo git dovolil dodajanje slike, iz datoteke `.gitignore` odstrani vrstico `*.jpg`.

Da ti bo delovalo poganjanje v Binderju, potrebuješ datoteko [`Dockerfile`](https://github.com/jaanos/APPR-2018-19/blob/master/Dockerfile), v kateri (na dveh mestih) nadomestiš `APPR-2018-19` z `APPR-2017-18`. Da bo delovala tudi povezava iz poročila, ki je trenutno zakomentirana, potrebuješ še datoteki [`lib/rstudio.r`](https://github.com/jaanos/APPR-2018-19/blob/master/lib/rstudio.r) in [`slike/RStudio.png`](https://github.com/jaanos/APPR-2018-19/blob/master/slike/RStudio.png) (iz `.gitignore` odstrani še vrstico `*.png`). Poleg tega bo treba popraviti še povezavi v `README.md`:
```markdown
* [![Shiny](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/MatijaGH/APPR-2017-18/master?urlpath=shiny/APPR-2017-18/projekt.Rmd) Shiny
* [![RStudio](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/MatijaGH/APPR-2017-18/master?urlpath=rstudio) RStudio
```

**Comment by MatijaGH** [comment]
Hvala za pomoč, vse sem naredil kot ste rekli, imam le še eno težavo, in sicer zemljevida v R-Studiu ne morem ustvariti, javlja mi napako: Error in maptools::unionSpatialPolygons: isTRUE(gpclibPermitStatus()) is not TRUE .
Zanimivo pa se zemljevid pokaže, ko zaženem projekt prek Binderja.
To in pa če imate še kakšno pripombo, drugače pa mislim, da je projekt končan in pripravljen na predstavitev.
Lep pozdrav

**Comment by jaanos** [comment]
Da ne bo prihajalo do napake, si namesti knjižnico `rgeos`.

Poročilo sicer pri meni deluje, tako da bom dodal povezavo na repozitorij za zagovore, z @alenFMF pa se lahko domeniš za termin zagovora, če se seveda še nisi. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

Imam sicer še naslednje pripombe:
* Slika se pri meni ne prikaže, saj jo imaš v mapi `Slike` (z veliko začetnico), medtem ko se na njo sklicuješ s potjo `slike/Nafta.jpg` (mala začetnica v imenu mape). Najlažje bo, če začetnico popraviš kar v kodi - če boš dodal še program `rstudio.r` (glej prejšnji odgovor), ga tudi ustrezno popravi.
* Na začetku razdelka *Analiza in vizualizacija podatkov* se na veliko izpiše koda - znak `#` v Markdownu namreč pomeni naslov, ne komentar (najbolje bo, da to kodo kar pobrišeš).
* Na grafih, kjer prikazuješ BDP (tako v poročilu kot v Shinyju), se na osi y pojavlja eksponentna notacija. Da se je znebiš, svetujem, da podatke deliš npr. s 1000000000 ter ustrezno popraviš oznako osi (npr. *BDP v milijardah dolarjev*).
* Pogrešam kakšno naprednejšo analizo. Na podatkih, ki jih imaš, bi se gotovo dalo narediti kakšen model, s katerim bi napovedoval, kako se bo določena vrednost spreminjala v prihodnosti.
* Povezave za Binder še niso popravljene (glej prejšnji odgovor).

**Comment by MatijaGH** [comment]
Hvala za odgovor, spremenil sem zadeve, ki ste jih omenili in dodal nekaj naprednejših analiz. Edino, česar mi ni uspelo je povezava za Binder s poročila, ki kar noče delovati, čeprav ne javi nobene napake.

**Comment by jaanos** [comment]
Kar se tiče povezave za Binder iz poročila, bo treba popraviti dve stvari:
* program `rstudio.R` ima veliko črko v končnici, zato ga bo treba kot takega klicati v poročilu, in
* v `rstudio.R` bo treba popraviti pot do slike, saj ima mapa `Slike` veliko začetnico (kot rečeno, velja isto za sliko v poročilu).

Povezava se bo prikazala samo pri poganjanju z Binderjem.

**Comment by jaanos** [comment]
Še to: svetujem, da dodaš parameter `warning=FALSE` še v glavo prvega bloka kode (tam, kjer kličeš `libraries.r`), sicer se pri poganjanju v Binderju izpiše še eno opozorilo.

**Comment by MatijaGH** [comment]
Sem naredil kot ste rekli in sedaj vse deluje brez problema. Hvala za pomoč. Ali bi lahko še posodobili povezavo na repozitoriju za zagovore?

**Comment by jaanos** [comment]
Sem posodobil.

**Comment by MatijaGH** [comment]
Hvala.
